### ISSUE TITLE
What and why

### ISSUE THREAD

**Issue by galeone** [galeone/bacup#1]
I want to start this project using Rust, so I have a good excuse to learn the language by having a project to complete.

## The idea

Backing up a whole VPS is stupid, backing up only the data might be a good idea, but the data we want to backup depends on the services hosted on the VPS; the problem is not trivial.

The obvious way of using rsync + systemd timers or whatever just bores me, and it's old and not trivially configurable (since everything depends on the services we want to backup).

### What to backup

What the user wants. There might be thousands of different scenarios, like:

- I have a database with PostgreSQL, I'd like to execute the `pg_dumpall` periodically and backup this dump.
- Same stuff with MySQL/MariaDB
- Redis? I need to copy the file
- Sqlite? Like Redis
- What about the configuration files? I usually need them.
- What if I have different services interacting with each other?
- What if I have a webserver? I should back up the web server configuration (e.g. nginx.conf and all the other parts of the configuration)
- What if I have a PHP website? A Python server?
- A Go application?

There are TONS of use cases, and every use case is completely user-dependent (e.g. I like to configure my system as I want, and my systems are almost completely customized. All the standard backup tools just don't work for me).

### Where to backup?

It depends. Do you like the cloud? I don't. But there's some good cheap storage on "the cloud", so you might be interested in backing up your stuff there.

- AWS
- Google Cloud Storage
- Other decent cloud providers
- My self-hosted server
- Are you a terrible person and you want to backup everything on git? (yeah GitHub has infinite free storage for small files...)

The self-hosted server can be trivial or can be something nice, a bacup client and a bacup server might be nice to have.

### How to backup

It should be trivial.

Every time I configure a new server, I should just:

- download the bacup client
- configure it
- start it as a background service and forgot about it

The configuration part should be trivial. I should be able to:

- define with a list the services I want to backup and how I want to backup them, something like
   ```yml
   foo:
      cloud: aws
      address: whatever
      authentication: the_token

   dbname:
      type: postgres
      what: cluster
      when: daily
      incremental: true
      where: foo
  ```

and if PostgreSQL is in some well-known location, then the `pg_dump_all -f filename.sql` can be executed every day, to create the backup file and once created upload it to the configured cloud provider.

With the same simplicity I should be able to backup: files (invoking rsync in the background if possible, why not), folders, and invoke the correct backup tool for the specified service (if it has it, like PostgreSQL).

So this is more or less the idea.

Any comment/suggestion is welcome.

The design of the software architecture will be in a different issue - this issue is only to brainstorm about the idea, the simplicity of usage, how it should work from the user point of view (yeah it's like a user-story, although I don't "love" all these agile things).

**Comment by galeone** [comment]
```toml
# remotes definitions
[aws]
    [aws.bucket_name]
    region = ""
    access_key = ""
    secret_key = ""

[gcloud]
    [gcloud.bucket1]
    service_account_path = ""

[ssh]
    [ssh.remote_host1]
    host = ""
    port = ""
    username = ""

[git]
    [git.github]
    host = ""
    port = ""
    username = ""

# what to backup. Service definition
    
[postgres]
    [postgres.service1]
    username = ""
    db_name = ""

[folder]
    [folder.service1]
    path = ""

# mapping services to remote

[backup]
    [backup.service1_db]
    what = "postgres.service1"
    where = "aws.bucket_name"
    when = "daily 01:00 GMT"
    remote_path = "/service1/database/"
    compress = "no"
    incremental = "yes"

    [backup.service1_source]
    what = "postgres.service1"
    where = "aws.bucket_name"
    when = "daily 01:00 GMT"
    remote_path = "/service1/source/"
    compress = "yes"
    incremental = "no"
```

This is the configuration design idea, it should be something like that
